from app.models import db, Post, environment, SCHEMA
from random import choice, sample, randint
from sqlalchemy.sql import text


# Adds a demo user, you can add other users here if you want
def seed_posts():
    seed_post1= Post(title="After Lost", image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796840/al_hkfzf2.jpg", description="In the quaint town of Eclipsia, where reality and the supernatural intertwine, a mysterious event known as 'The Vanishing' shrouds the community in an enigmatic veil. As the town grapples with the aftermath of unexplained disappearances, a group of individuals with disparate backgrounds finds themselves entangled in a web of secrets that transcend the boundaries of the known world.", user_id=randint(1, 10))
    seed_post2= Post(title="Ajin Demi Human",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796841/adh_t6xfmg.png", description="In a world where immortality takes a sinister form, 'Ajin: Demi-Human' unfolds a gripping narrative of fear, discrimination, and the thin line that separates humanity from inhumanity. The discovery of Ajin, a rare breed of beings with the ability to regenerate indefinitely, shatters the conventional understanding of life and death.")
    seed_post3 = Post(title="Am I actually the Strongest",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796840/aiats_slzfsk.avif", description="In a world where strength is measured not only in physical prowess but in the resilience of one's spirit, 'Am I Actually the Strongest?' introduces us to a protagonist with an unparalleled determination to rise above the challenges that fate throws their way. Ryuji Kurogane, an ordinary high school student, discovers a hidden power within himself that catapults him into a realm of extraordinary abilities. As word spreads of his unprecedented strength, Ryuji becomes a focal point in a world teeming with magic, mythical creatures, and rival warriors vying for the title of the ultimate champion.")
    seed_post4 = Post(title="Assasination Classroom",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796843/ac_kze8lg.jpg", description="In a high school unlike any other, where the fate of the world rests on the shoulders of an unlikely group of students, 'Assassination Classroom' delivers a unique blend of action, humor, and heartwarming moments. The story begins when a mysterious creature, claiming to be a powerful octopus-like being, destroys 70% of the moon and promises to do the same to Earth within a year. The twist? This creature, known as Koro-sensei, becomes the homeroom teacher for Class 3-E at Kunugigaoka Junior High School. The government's solution: task the students with the seemingly impossible mission of assassinating their otherworldly teacher before he carries out his threat.")
    seed_post5 = Post(title="Attack on Titan",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796840/aot_geivwa.jpg", description="In a high school unlike any other, where the fate of the world rests on the shoulders of an unlikely group of students, 'Assassination Classroom' delivers a unique blend of action, humor, and heartwarming moments. The story begins when a mysterious creature, claiming to be a powerful octopus-like being, destroys 70% of the moon and promises to do the same to Earth within a year. The twist? This creature, known as Koro-sensei, becomes the homeroom teacher for Class 3-E at Kunugigaoka Junior High School. The government's solution: task the students with the seemingly impossible mission of assassinating their otherworldly teacher before he carries out his threat.")
    seed_post6 = Post(title="Atelier Ryza",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796839/ared_t7mmoc.webp", description="In the serene village of Kurken, where the air is filled with the scent of alchemical wonders, a spirited and imaginative young girl named Ryza dreams of a life beyond the ordinary. One day, her fate takes an unexpected turn when she discovers an ancient secret that unveils the hidden potential of alchemy. Joined by her close friends, the shy but determined Tao and the adventurous Lent, Ryza embarks on a quest to unravel the mysteries of alchemy and explore the uncharted realms surrounding her village. Their journey takes them through lush landscapes, mysterious ruins, and encounters with fantastical creatures.")
    seed_post7 = Post(title="Akame Ga Kill",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796840/agk_kgn0b0.webp", description="In a land engulfed by corruption and tyranny, 'Akame ga Kill!' unveils a gripping tale of rebellion, morality, and the price of justice. When naive young warrior Tatsumi ventures to the capital with dreams of making a difference, he is quickly thrust into a world where morality is a luxury, and survival demands ruthless choices.")
    seed_post8 = Post(title="Akudame Drive",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796841/ad_jj2ngp.jpg", description="In a neon-lit metropolis governed by chaos and crime, 'Akudama Drive' propels viewers into a dystopian future where the line between justice and anarchy is razor-thin. Set against a backdrop of high-tech cityscapes and lawless districts, the anime follows a disparate group of individuals known as 'Akudama,' each possessing extraordinary skills and a penchant for breaking the law.")
    seed_post9 = Post(title="Afro Samurai",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796837/as_qxmbb8.jpg", description="In a world that blends futuristic technology with ancient samurai traditions, 'Afro Samurai' weaves a tale of vengeance, honor, and the relentless pursuit of a man known only as Afro. Set against a visually striking backdrop, this anime introduces viewers to a world where the strongest swordsman carries the burden of his past sins and seeks redemption through a path soaked in blood.")
    seed_post10 = Post(title="Ayaka: A Story of Bonds and Wounds",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796845/aasobaw_zc9jvb.webp", description="In the serene town of Hikari, where cherry blossoms whisper tales of love and resilience, 'Ayaka: Bonds and Wounds' unravels a heartfelt narrative woven with the threads of friendship, romance, and the healing power of time.")
    seed_post11=Post(title="Basilisk",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796836/basi_h5y4zb.jpg", description="Set against the backdrop of ancient Japan, where feuding clans and political intrigue create a volatile landscape, 'Basilisk: The Kouga Ninja Scrolls' delivers a tale of love, betrayal, and deadly conflict. The Iga and Kouga ninja clans, bound by a fragile truce, find themselves thrust into a deadly competition when the Tokugawa shogunate orders a brutal showdown to determine the next ruler.")
    seed_post12 = Post(title="Bastard",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796836/b_wwkdaw.webp", description="In a world where magic, monsters, and mayhem collide, 'Bastard!!' introduces viewers to a fantastical realm teetering on the edge of chaos. This irreverent and action-packed anime follows the adventures of the enigmatic dark wizard Dark Schneider, a rogue with a penchant for trouble and an insatiable appetite for both women and magical mischief.")
    seed_post13 = Post(title="Brserk",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796835/ber_yf1y6j.webp", description="In a world shrouded in darkness and despair, where demons roam and the line between humanity and monstrosity blurs, 'Berserk' unfolds the epic and tragic tale of Guts, a lone mercenary with a brutal past, and his relentless quest for purpose and survival.")
    seed_post14 =Post(title="Beyond The Boundary",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796835/btb_ryxhiz.jpg", description="In a world where the boundary between the supernatural and the mundane is as fragile as a wisp of air, 'Beyond the Boundary' invites viewers on a mesmerizing journey filled with magic, romance, and the delicate balance between life and the supernatural.")
    seed_post15 =Post(title="B: The Beginning",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796834/Btbeg_fouuyk.webp", description="In the futuristic city of Cremona, where advanced technology and ancient mysteries coexist, 'B: The Beginning' unfolds a complex narrative blending crime, intrigue, and supernatural elements. As a mysterious serial killer emerges, a brilliant detective and an enigmatic vigilante become entangled in a web of conspiracies that threaten to plunge the city into chaos.")
    seed_post16 = Post(title='Black Clover', image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796836/bc_tgapsn.jpg" ,description="Asta and Yuno were abandoned at the same church on the same day. Raised together as children, they came to know of the 'Wizard King'—a title given to the strongest mage in the kingdom—and promised that they would compete against each other for the position of the next Wizard King. However, as they grew up, the stark difference between them became evident. While Yuno is able to wield magic with amazing power and control, Asta cannot use magic at all and desperately tries to awaken his powers by training physically. When they reach the age of 15, Yuno is bestowed a spectacular Grimoire with a four-leaf clover, while Asta receives nothing. However, soon after, Yuno is attacked by a person named Lebuty, whose main purpose is to obtain Yuno's Grimoire. Asta tries to fight Lebuty, but he is outmatched. Though without hope and on the brink of defeat, he finds the strength to continue when he hears Yuno's voice. Unleashing his inner emotions in a rage, Asta receives a five-leaf clover Grimoire, a 'Black Clover' giving him enough power to defeat Lebuty. A few days later, the two friends head out into the world, both seeking the same goal—to become the Wizard King!", user_id="1")
    seed_post17 = Post(title="Bleach",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796835/blea_zvoyvm.avif", description="In the bustling city of Karakura, where spirits and malevolent entities lurk in the shadows, 'Bleach' introduces us to Ichigo Kurosaki, an ordinary teenager with an extraordinary destiny. When Ichigo inadvertently acquires the powers of a Soul Reaper, his life takes an unexpected turn, thrusting him into a world where the living and the dead collide in epic battles and unforeseen alliances.")
    seed_post18 = Post(title="Blue Dragon",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796835/blud_ab78mp.jpg", description="Embark on a thrilling journey to the magical world of Blue Dragon, where the boundaries between reality and imagination blur, and the fate of an entire civilization rests on the shoulders of a few unlikely heroes. 'Blue Dragon' follows the epic quest of Shu and his friends as they confront dark forces, unravel ancient mysteries, and discover the true power that lies within.")
    seed_post19=Post(title="Blue Exorcist",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796836/be_htotpx.jpg", description="In the bustling city of True Cross Academy, where humans and demons coexist unbeknownst to the ordinary populace, 'Blue Exorcist' unfolds the extraordinary tale of Rin Okumura. Born the son of Satan, Rin discovers his demonic heritage when a tragic incident pushes him to the brink. Determined to defy his infernal lineage, Rin enrolls in True Cross Academy to become an exorcist and battle the very forces that threaten to consume him.")
    seed_post20 = Post(title="Burn The Witch",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796832/btw_ahmdp1.jpg", description="Set in the hidden realm of Reverse London, where mystical creatures and supernatural entities coexist with the mundane, 'Burn the Witch' introduces viewers to the elite duo of witches tasked with maintaining the balance between the magical and non-magical worlds. As they take on otherworldly challenges, their extraordinary adventures unfold against the backdrop of a vibrant and fantastical cityscape.")
    seed_post21 = Post(title="Bungo Stray Dog",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796835/bsd_agwhlg.webp", description="In the shadowy underworld of Yokohama, where supernatural abilities and criminal enterprises collide, 'Bungo Stray Dogs' introduces a group of gifted individuals with extraordinary powers. These individuals, known as the Armed Detective Agency and the Port Mafia, navigate a precarious balance between justice and chaos, unraveling mysteries and facing formidable adversaries along the way.")
    seed_post22 =Post(title="Cautious Hero",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796831/ch_whrnva.jpg", description="Prepare for a hilarious and unconventional take on the isekai genre with 'Cautious Hero', where the fate of worlds rests in the hands of the overly cautious and incredibly powerful hero, Seiya Ryuuguuin. Summoned to a fantasy realm to save it from impending doom, Seiya approaches his quest with an excess of caution, leaving no room for surprises or risks.")
    seed_post23= Post(title="Chained Soldier",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796830/cs_vsmwya.jpg", description="One day, Yuuki Wakura, a recent high school graduate, stumbles inside a gate and meets Kyouka Uzen, the commander of the 7th squad of the Demon Defense Force. Kyouka has the power to 'enslave' Shuuki and mount them for combat, but cornered by an increasing number of Shuuki, she asks Yuuki if she can enslave him.")
    seed_post24 = Post(title="Charlotte",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796831/char_jv18n7.jpg", description="'Charlotte' weaves a poignant narrative set in a world where a small percentage of adolescents manifest superhuman abilities, only to lose them as they enter adulthood. Amidst the secrets of these fleeting powers lies Hoshinoumi Academy, a school dedicated to sheltering and guiding these extraordinary individuals. Yuu Otosaka, a seemingly ordinary student, becomes entangled in a series of events that thrust him into the heart of a compelling story exploring the consequences of extraordinary abilities.")
    seed_post25 = Post(title="Code Geass",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796831/cg_pwvohz.jpg", description="In an alternate future where the Holy Britannian Empire dominates the world with oppressive force, 'Code Geass: Lelouch of the Rebellion' unveils a gripping tale of rebellion, power, and the consequences of wielding extraordinary abilities. Caught in the crossfire is Lelouch vi Britannia, a disgraced prince with a thirst for revenge and a mysterious power that could reshape the destiny of nations.")
    seed_post26 = Post(title="Classroom of the Elite",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796840/coe_yr9eot.png", description="In the prestigious Koudo Ikusei Senior High School, excellence is not merely encouraged; it's the sole criterion for success. 'Classroom of the Elite' unfolds a compelling narrative within the walls of this elite institution, where societal expectations, personal ambitions, and the facade of perfection conceal the darker truths that lie beneath the surface.")
    seed_post27 = Post(title="Cowboy Bebop",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796832/cb_w2navr.webp", description="'Cowboy Bebop' ventures into the vastness of space, blending a jazz-infused soundtrack with a narrative that seamlessly intertwines bounty hunting, existentialism, and the consequences of a turbulent past. Follow the crew of the spaceship Bebop—Spike Spiegel, Jet Black, Faye Valentine, Edward, and Ein—as they navigate the bounty hunter life, confronting their own demons against a backdrop of intergalactic adventures.")
    seed_post28 = Post(title="Cyberpunk EdgeRunners",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796831/cp_gp2beb.jpg", description="Cyberpunk: Edgerunners tells a standalone, 10-episode story about a street kid trying to survive in a technology and body modification-obsessed city of the future. Having everything to lose, he chooses to stay alive by becoming an edgerunner—a mercenary outlaw also known as a cyberpunk.")
    seed_post29 = Post(title="Daily Life of the Immortal King",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796828/dlotik_pctcwc.webp", description="In a realm where cultivation and mystical powers reign supreme, 'The Daily Life of the Immortal King' introduces us to Wang Ling, a seemingly ordinary high school student with an extraordinary secret—he's an immortal cultivator with powers beyond imagination. As he navigates the challenges of school life, hidden enemies, and the responsibilities of his celestial lineage, Wang Ling's daily routine becomes anything but mundane.")
    seed_post30= Post(title="Dark Gathering",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796831/dg_utxzh7.webp", description="Keitaro, who's always had a disposition for attracting spirits, gets hired as a tutor for a little girl named Yayoi who can see spirits and is searching for the spirit that took away her mother.")
    seed_post31 = Post(title="Darker Than Black",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796827/dtb_uydnuo.jpg", description="In the enigmatic aftermath of a mysterious catastrophe known as 'Heaven's Gate', supernatural anomalies and superpowered individuals, known as Contractors, emerge in the shadows. 'Darker Than Black' unfolds a complex narrative where morality is a luxury, and every action comes at a price. Follow the stoic Hei, an elite Contractor known as the Black Reaper, as he navigates a treacherous world of espionage, intrigue, and a web of secrets that stretch beyond the realms of human comprehension.")
    seed_post32 = Post(title="Darwin's Game",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1702233602/darg_gflli5.jpg", description="In the digital underworld of 'Darwin's Game', an innocuous mobile app transforms into a deadly survival game, pitting players against each other in a fight for survival. Kaname Sudou, an unsuspecting high school student, finds himself thrust into this life-or-death competition. As he grapples with the harsh realities of the game and the mysterious organization behind it, Kaname must adapt, strategize, and uncover the secrets that shroud Darwins Game.")
    seed_post33 = Post(title="Death Note",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796827/dn_epn8ob.jpg", description="'Death Note' weaves a dark and gripping tale that transcends the boundaries of morality and the consequences of absolute power. When high school student Light Yagami stumbles upon a mysterious notebook—the Death Note—his life takes a chilling turn. Possessed by the power to kill anyone by simply writing their name in the Death Note, Light sets out on a perilous journey to reshape the world according to his own vision of justice.")
    seed_post34 = Post(title="Death Parade",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796827/dp_dgqpff.avif", description="In the ethereal realm between life and death, souls arrive at the mysterious Quindecim bar, where the enigmatic bartender, Decim, presides over a peculiar game. Welcome to 'Death Parade', a thought-provoking anime that explores the complexities of human nature as the departed undergo judgment and reveal their true selves in a high-stakes contest that transcends life and death.")
    seed_post35 = Post(title="Deadman Wonderland",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796827/dw_zj3ct4.webp", description="In a dystopian future where an earthquake has laid waste to Tokyo, 'Deadman Wonderland' emerges as a nightmarish prison that combines public amusement with brutal incarceration. Ganta Igarashi, a young survivor of the disaster, finds himself wrongfully accused of a gruesome crime and sentenced to the twisted world of Deadman Wonderland. As Ganta navigates the macabre challenges within the prison, he discovers dark secrets, uncovers supernatural abilities, and becomes embroiled in a deadly conspiracy.")
    seed_post36 = Post(title = "Delicious in Dungeon",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796832/did_hwkbvw.webp", description="Embark on a culinary adventure like no other in 'Delicious in Dungeon', where the delectable meets the dangerous. When a group of adventurers loses a companion to a dragon in a perilous dungeon, they must make a unique choice: delve deeper into the labyrinthine depths or abandon their fallen comrade. Opting for an unconventional approach, they decide to cook and consume the monsters that inhabit the dungeon, transforming their quest into a gastronomic delight.")
    seed_post37 = Post(title="Demon Slayer",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796828/ds_xd8afn.webp", description="'Demon Slayer: Kimetsu no Yaiba' transports viewers to Taisho-era Japan, where Tanjiro Kamado's peaceful life is shattered when his family is slaughtered by demons, and his sister, Nezuko, is transformed into one. Driven by a fierce determination to avenge his family and find a cure for his sister, Tanjiro joins the Demon Slayer Corps, an elite group of warriors tasked with eradicating demons and uncovering the secrets of the supernatural world.")
    seed_post38 = Post(title="Dororo",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796827/doro_qkgepo.jpg", description="Set against the backdrop of the tumultuous Sengoku period in Japan, 'Dororo' unfolds a tale of revenge, redemption, and the struggle for humanity. Lord Daigo Kagemitsu, driven by ambition, sacrifices his newborn son's body to demons in exchange for power. However, the child survives, becoming Dororo, a young, prosthetic-armed thief, and Hyakkimaru, a wandering swordsman seeking to reclaim his stolen limbs and organs from the demons that now inhabit them.")
    seed_post39 = Post(title="Eden's Zero",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796827/ez_x6frnv.jpg", description="'Edens Zero' takes viewers on a thrilling intergalactic journey to a vast cosmos where adventure, friendship, and the pursuit of dreams unfold amidst the stars. In the Sakura Cosmos, a young boy named Shiki Granbell, raised by robots on the abandoned theme park planet of Granbell, dreams of exploring the universe. His life takes an unexpected turn when a celestial being, Rebecca Bluegarden, and her talking cat companion, Happy, arrive on Granbell. Together, they embark on a grand adventure aboard the spaceship Edens Zero, encountering a myriad of planets, challenges, and powerful foes." )
    seed_post40=Post(title="ERASED",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796830/e_qtrf52.png", description="'ERASED' follows the life of Satoru Fujinuma, an aspiring manga artist with an extraordinary ability called 'Revival'. This power allows him to go back a few minutes in time to prevent accidents and save lives. However, when tragedy strikes close to home, Satoru is unexpectedly thrust back in time by 18 years to his childhood, a pivotal period marked by a series of kidnappings and murders. Tasked with uncovering the truth and preventing a tragic fate, Satoru must confront his past and unravel the mysteries that haunt his life.")
    seed_post41 = Post(title="Elfin Lied",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796826/el_xqosrj.jpg", description="'Elfen Lied' unravels a haunting narrative that explores the complexities of humanity, cruelty, and the consequences of unchecked scientific experimentation. Lucy, a mysterious and powerful Diclonius—a mutant with telekinetic abilities and lethal invisible arms—escapes from a government research facility, leaving a trail of violence in her wake. As Lucy's past intertwines with that of Kouta, a university student, and Yuka, his cousin, the dark secrets of the Diclonius race and the inhumanity of human nature are laid bare.")
    seed_post42 = Post(title="Fairy Tail",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796822/ft_ioaye3.jpg", description="In the magical land of Fiore, where wizards wield incredible powers and embark on thrilling adventures, 'Fairy Tail' stands as a guild renowned for its camaraderie, strength, and unyielding spirit. Follow the journey of Natsu Dragneel, a fiery and enthusiastic Dragon Slayer, along with his friends Lucy Heartfilia, Gray Fullbuster, Erza Scarlet, and Happy the Exceed cat, as they take on perilous missions, battle formidable foes, and forge unbreakable bonds.")
    seed_post43 = Post(title="Fate Zero",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796822/fz_tv61j6.jpg", description="In the heart of Fuyuki City, an ancient ritual known as the Holy Grail War is about to unfold, where mages and their summoned heroic spirits engage in a ruthless battle for the coveted Holy Grail—a mystical artifact capable of granting any wish. 'Fate/Zero' serves as a prequel to the renowned Fate/stay night series, delving into the dark and intricate origins of this deadly contest. As seven masters and their heroic servants clash in a high-stakes war, the boundaries between justice and morality blur, unveiling the harsh realities of ambition, sacrifice, and the consequences of wielding great power.")
    seed_post44 = Post(title="Fire Force",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796826/ff_u31aza.jpg", description="In a world where spontaneous human combustion turns people into living infernos known as Infernals, 'Fire Force' introduces the Special Fire Force, a group of skilled pyrokinetic firefighters tasked with extinguishing these supernatural flames and uncovering the mysterious phenomenon behind them. Follow Shinra Kusakabe, a young firefighter with the unique ability to control and project fire, as he joins Special Fire Force Company 8. Together, they navigate a city engulfed in both literal and metaphorical flames, facing Infernals, dark conspiracies, and a sinister force threatening to plunge the world into chaos")
    seed_post45 = Post(title="Fruit Basket",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796826/fb_pboe8m.webp", description="'Fruits Basket' follows the poignant and heartwarming story of Tohru Honda, a kind-hearted and resilient high school girl who, after a series of unfortunate events, finds herself living with the mysterious Sohma family. Unbeknownst to Tohru, the Sohmas are bound by a powerful curse that transforms them into animals from the Chinese zodiac when hugged by someone of the opposite gender. As she becomes entwined in the lives of the Sohmas, Tohru discovers the complexities of love, friendship, and the profound impact of breaking free from the chains of the past.")
    seed_post46 = Post(title="Fruit of Evolution",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796823/foe_uysjqc.webp", description="High school student Hiiragi Seiichi is bullied by his classmates for being a 'loser'. One day, his entire school is suddenly transported to a video game-like world of swords and sorcery. When he accidentally eats 'the Fruit of Evolution', his life as a successful 'winner' begins.")
    seed_post47 = Post(title="Full Metal Alchemist",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796823/fm_j6wqkd.webp", description="Set in the early 20th century, in a fictional universe in which alchemy is a widely practiced science, the series follows the journey of two alchemist brothers, Edward and Alphonse Elric, who are searching for the philosopher's stone to restore their bodies after a failed attempt to bring their mother back to life ...")
    seed_post48 = Post(title="Full Metal Alchemist: Brotherhood",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796823/fmab.jpg_zvd2vp.jpg", description="'Fullmetal Alchemist: Brotherhood' is an epic tale set in a world where alchemy is a powerful and mysterious science. The story revolves around two brothers, Edward and Alphonse Elric, who, after a failed alchemical ritual to bring their mother back to life, suffer dire consequences. Edward loses his left leg, and in a desperate attempt to save his brother, sacrifices his right arm to bind Alphonse's soul to a suit of armor. Determined to restore their bodies, the brothers embark on a perilous journey to find the Philosopher's Stone, an ancient artifact with the power to amplify alchemical abilities.")
    seed_post49 = Post(title = "The Future Diary",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796826/fd.jpg_zpc6g4.webp", description="'Mirai Nikki', also known as 'The Future Diary', is a psychological thriller that immerses viewers in a high-stakes survival game orchestrated by the mysterious Deus Ex Machina. Yukiteru Amano, an introverted high school student, discovers that his cellphone diary predicts the future. However, he soon realizes he's not the only one with this ability. Twelve individuals, each possessing a unique diary predicting different aspects of the future, are thrust into a deadly competition where the last survivor will become the next god of time and space.")
    seed_post50 = Post(title="Gangsta",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796822/g_t7i6cs.webp", description="In the crime-ridden city of Ergastulum, where corruption and organized crime thrive, 'Gangsta' follows the lives of two 'Handymen' for hire: Worick Arcangelo, a former gigolo with a mysterious past, and Nicolas Brown, a deaf mercenary with incredible combat skills. Together, they navigate the dangerous underbelly of Ergastulum, taking on jobs ranging from mediation to elimination. As they become entangled in the conflicts between powerful criminal families, government agencies, and the genetically enhanced 'Twilights', Worick and Nicolas must confront their own dark histories while trying to survive in a city on the brink of chaos.")
    seed_post51 = Post(title="The Gene of A.I.",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1702234950/goai_ymgbtr.webp", description="A doctor who treats robot and humanoid problems takes place in the near future when humanoids with AI account for 10% of the population.")
    seed_post52 = Post(title="Gintama",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796823/gin_yc8t3d.jpg", description="'Gintama' is a uniquely eccentric and comedic anime set in an alternate-history Edo period where Earth has been invaded by extraterrestrial beings known as the Amanto. Despite the changes to their world, samurai still exist, and the protagonist, Gintoki Sakata, runs the Odd Jobs business. Alongside his friends Shinpachi Shimura and Kagura, Gintoki navigates the challenges of odd requests, intergalactic threats, and the comedic chaos that ensues in a world blending historical, sci-fi, and absurd elements.")
    seed_post53= Post(title="God of High School",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796821/gohs_psitjx.jpg", description="'The God of High School' centers around Jin Mori, a high school student and skilled martial artist with an insatiable appetite for fighting. The story unfolds as Mori and his friends, the fiery swordswoman Yu Mira and the strategic tactician Han Daewi, participate in 'The God of High School' tournament—an event that promises the winner a wish of their choosing. As they face powerful opponents from various martial arts disciplines, dark conspiracies emerge, revealing a world filled with divine powers, ancient secrets, and the quest for ultimate strength.")
    seed_post54 = Post(title="Gurren Lagann",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796821/gl_taemn9.jpg", description="In a world where humanity lives underground to escape the oppression of the Spiral King, 'Tengen Toppa Gurren Lagann' follows the story of Simon, a young digger with dreams as vast as the sky. When he discovers a mysterious mecha, Lagann, and teams up with the charismatic and larger-than-life Kamina, their lives take an extraordinary turn. Together with a group of rebels, they embark on a journey to the surface, facing colossal enemies, uncovering ancient secrets, and embracing the indomitable spirit that propels them to unimaginable heights.")
    seed_post55 = Post(title="The Great Cleric",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796821/gc_wf7y8u.jpg", description="A young japanese salaryman is killed by a gunshot and reincarnated by a goddess in an alternate, fantasy-like world as Luciel, a teenager blessed with healing magic. To make sure that this time he lives a long and happy life, Luciel works hard to improve himself.")
    seed_post56 = Post(title="Grimgar of Ashes and Illusion",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796821/gaai_n6dl8o.png", description="'Hai to Gensou no Grimgar' transports viewers to a mysterious world where a group of strangers wakes up with no memory of their past lives. The only remnants of their former existence are their names. Struggling to survive in a fantastical realm filled with monsters and magic, the group forms an uneasy alliance and takes on the roles of adventurers. As they navigate this new reality, facing challenges, forging bonds, and discovering their own strengths and weaknesses, the line between illusion and reality becomes blurred in their quest for survival.")
    seed_post57 = Post(title="Helck",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796821/h_zyrq7z.jpg", description="In a world plagued by conflict between humans and demons, 'Helck' introduces a powerful and enigmatic hero named Helck. Unlike the typical demon antagonist, Helck surprises everyone by volunteering to participate in the Hero's Selection Tournament—an event that determines the next hero to stand against the demon threat. As Helck's true motives and unparalleled strength come into question, he forms an unlikely alliance with the kind-hearted human princess Vamirio, embarking on a journey that unveils the complex dynamics between humans and demons and challenges the very notions of good and evil.")
    seed_post58 = Post(title="Hell's Paradise", image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701797548/hp_ta1t6n.png",description="After being sentenced to death, ninja Gabimaru the Hollow finds himself apathetic. After leading a blood-soaked life, Gabimaru believes he deserves to die. However, every attempt to execute him inexplicably fails. Finally, Sagiri Yamada Asaemon, a fledgling member of a famed executioner clan, is asked to take Gabimaru's life; yet Sagiri makes no move to kill him as requested. Insisting that Gabimaru will not die because of his love for his wife, Sagiri instead offers him the chance to obtain a full pardon for his crimes. If he can travel to the island of Shinsekyo and obtain the Elixir of Life—which supposedly grants immortality—and bring it back for the shogun, then his freedom will be assured. But of the many who have traveled to Shinsekyo in search of the mythical Elixir, not a single person has returned sound of mind, if at all. Though unaware of the numerous dangers ahead, Gabimaru decides to accept the offer—alongside ten other death row convicts—in hope that he and his wife may finally live in peace.",user_id="4")
    seed_post59 = Post(title="Hellsing Ultimate",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796819/hu_qutjgz.jpg", description="'Hellsing Ultimate' thrusts viewers into a world where supernatural threats, particularly vampires, pose a grave danger to humanity. The Hellsing Organization, led by the enigmatic Sir Integra Hellsing, is tasked with protecting England from these malevolent forces. At the heart of their arsenal is Alucard, an ancient and immensely powerful vampire who serves as the organization's ultimate weapon. As dark conspiracies unfold, Hellsing faces increasingly formidable foes, including rival organizations and ancient evils that threaten to plunge the world into chaos." )
    seed_post60 = Post(title="Hero Classroom",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796821/hc_h8x02v.avif", description="This prestigious school specializes in training future heroes destined to protect humanity. Among them is Earnest Flaming, a young girl with unmatched skill who holds the highest record. But her reign at the top is challenged when she's assigned to mentor a new and carefree student, Blade, whose power rivals her own!")
    seed_post61 = Post(title="Hunter x Hunter",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796819/hxh_vew7ne.jpg", description="'Hunter x Hunter' follows the exhilarating journey of Gon Freecss, a young boy who aspires to become a Hunter—a special and elite class of individuals who undertake dangerous tasks such as capturing criminals, searching for treasures, and exploring uncharted territories. Gon's motivation is deeply rooted in finding his long-lost father, Ging Freecss, who is a legendary Hunter. Along the way, he forges strong friendships with individuals like Killua Zoldyck, Kurapika, and Leorio, as they face perilous challenges, uncover dark secrets, and participate in the rigorous Hunter Exam.")
    seed_post62 = Post(title="Hitori No SHita",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796821/hns_atryew.webp", description="'Hitori no Shita: The Outcast' follows the story of Chou Soran, a college student who becomes entangled in a world of supernatural phenomena and martial arts. After a chance encounter with a mysterious girl named Fuu Houhou, Soran discovers that he possesses unique powers connected to an ancient martial art known as 'Koukaku', awakening dormant abilities within him. As he delves deeper into the world of the 'Outsiders', individuals with supernatural powers, Soran must navigate political intrigue, ancient secrets, and confront powerful adversaries to uncover the truth about his newfound abilities.")
    seed_post63 = Post(title="Horiyama",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796820/hor_t4gjfb.png", description="Horimiya revolves around the endearing duo, Kyouko Hori and Izumi Miyamura. Hori, the popular and seemingly perfect student, and Miyamura, the introverted and nerdy outcast, discover each other's true selves and fall madly in love.")
    seed_post64 = Post(title="I Don't Want To Get Hurt So I Maxed Out My Defense",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796820/idw_f43ins.avif", description="'I Don't Want to Get Hurt, so I'll Max Out My Defense' follows the gaming escapades of Kaede Honjou, a casual gamer who decides to venture into a virtual reality MMORPG titled 'NewWorld Online'. Unlike most players who focus on offense, Kaede decides to adopt a unique strategy—maxing out her defense stat to avoid any harm. Little does she know that her unconventional approach to the game will lead her on a hilarious and unexpected adventure, making her an unwitting force to be reckoned with in a world filled with monsters, quests, and powerful adversaries.")
    seed_post65 = Post(title="Initial D",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796819/id_byfdqg.jpg", description="'Initial D' takes viewers into the high-stakes world of street racing in the mountains of Gunma Prefecture, Japan. The story revolves around Takumi Fujiwara, a seemingly ordinary high school student with exceptional driving skills. Unbeknownst to Takumi, his nightly deliveries for his father's tofu shop have honed his abilities to perfection on the winding mountain roads. When his talent attracts the attention of the local racing scene, Takumi is thrust into the exhilarating and dangerous world of street racing, where he must prove himself against skilled opponents and rival racing teams." )
    seed_post66 = Post(title="Jujutsu Kaisen",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796820/jk_gmcya6.jpg", description="'Jujutsu Kaisen' unfolds the story of Yuji Itadori, a high school student with extraordinary physical abilities but a strong aversion to anything that requires effort. When his grandfather's ancient cursed artifact, a rotting finger, is accidentally unsealed, it unleashes a slew of malicious Curses into the world. In a twist of fate, Yuji finds himself entangled in the dangerous world of Curses, Jujutsu Sorcerers, and a cursed school. To protect his friends and confront the growing threat, Yuji joins forces with the enigmatic Jujutsu Sorcerer, Satoru Gojo, to learn the art of Jujutsu and battle Curses that threaten to devour humanity.")
    seed_post67 = Post(title="Kakeguri",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796816/kake_thk8ct.jpg", description="'Kakegurui' takes place in Hyakkaou Private Academy, an institution where social status is determined by one's gambling prowess. The students of Hyakkaou are no ordinary students; they are the future leaders and elites of society. Into this high-stakes environment arrives Yumeko Jabami, a seemingly innocent and unassuming transfer student. However, beneath her exterior lies a thrill-seeker who craves the excitement of high-stakes gambling. As Yumeko challenges the hierarchy of the student council and engages in intense gambling matches, the academy becomes a battleground of wits, deceit, and psychological manipulation.")
    seed_post68 = Post(title="Kill La Kill",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796815/klk_r7tmla.jpg", description="'Kill la Kill' is a high-octane, visually stunning anime set in the fictional Honnouji Academy, an institution ruled with an iron fist by the powerful and dictatorial Student Council President, Satsuki Kiryuin. The story follows Ryuko Matoi, a fierce and determined transfer student armed with half of a scissor-shaped weapon seeking answers about her father's death. Ryuko discovers the existence of powerful uniforms known as 'Goku Uniforms', which grant superhuman abilities to their wearers. Her quest for the truth leads her into a heated confrontation with Satsuki and the mysterious fabric known as Life Fibers, resulting in epic battles, personal growth, and a rebellion against the oppressive system.")
    seed_post69 = Post(title="Kingdoms of Ruin",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796815/kor_cfyw0x.webp", description="The rapid explosion of human technology has caused humanity to grow to fear and resent the divinely granted supernatural powers of witches. The witch Chloe and her apprentice, Adonis, find themselves caught in the crosshairs of the Redia Empire.")
    seed_post70=  Post(title="The Lengendary Hero is Dead",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796814/lhid_aatd3b.webp", description="Touka is a perverted farmer stuck masquerading as the legendary hero due to a young necromancer putting his soul in the guy's corpse. Now this woefully under-prepared doofus has to save the world despite having mana levels equaling that of an infant, and being unable to wield the hero's legendary sword properly.")
    seed_post71 = Post(title="Link Click",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796815/lc_fwzcv7.webp", description="Cheng Xiaoshi and Lu Guang run Time Photo Studio and accept requests from clients to relieve them of regrets. Through a photo provided by the client, Cheng Xiaoshi can travel back in time to the moment it was taken and assumes the identity of its photographer, with him absorbing the photographer's memories and emotions")
    seed_post72 = Post(title="Masamun Kun No Revenge",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1702236231/mkr_qasdn3.jpg", description="Seeking revenge against his tormentor, Masamune works hard to improve himself and returns as an incredibly handsome, albeit narcissistic, high school student. When he encounters Aki once again, he is prepared to exact vengeance.")
    seed_post73 = Post(title="Mashle",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796814/m_hxbls6.jpg", description="Into a world of magicians is born Mash, a young boy who lacks magic but is the strongest person around. His existence and destiny will change his world. Into a world of magicians is born Mash, a young boy who lacks magic but is the strongest person around. His existence and destiny will change his world.")
    seed_post74 = Post(title="Mob Psycho 100",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796814/mp_hdvrto.jpg", description="'Mob Psycho 100' revolves around Shigeo Kageyama, commonly known as 'Mob', a seemingly average middle school student. However, Mob possesses extraordinary psychic abilities that can cause mayhem if left unchecked. In an effort to lead a normal life and control his powers, Mob suppresses his emotions and avoids using his psychic abilities. Despite his reserved demeanor, Mob's life takes an unexpected turn when he encounters Arataka Reigen, a self-proclaimed psychic expert. Together, they navigate the challenges of the supernatural, facing evil spirits, other psychic threats, and uncovering the true nature of Mob's extraordinary powers.")
    seed_post75 = Post(title="Mobile Suit Gundam",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796813/msg_wvzi9w.jpg", description="'Mobile Suit Gundam' is a seminal mecha anime series set in a distant future where humanity has colonized space. The Earth Federation is engaged in a conflict with the Principality of Zeon, a group seeking independence for space colonies. The war introduces the use of giant humanoid robots known as mobile suits, revolutionizing warfare. The story follows Amuro Ray, a civilian caught in the conflict, who unexpectedly finds himself piloting the advanced mobile suit Gundam. As Amuro becomes a pivotal figure in the war, he grapples with the complexities of morality, the horrors of war, and the responsibilities that come with wielding such powerful technology.")
    seed_post76 = Post(title="Monster",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796814/mon_bwfdnj.avif", description="'Monster' is a gripping psychological thriller that follows the story of Dr. Kenzo Tenma, a highly skilled neurosurgeon living in Germany. His life takes a dark turn when he faces a moral dilemma: save the life of a talented young boy named Johan Liebert or the mayor of the town. Tenma decides to save Johan, a decision that sets off a chain of events leading to mysterious deaths, conspiracies, and the pursuit of a sociopathic killer. As Tenma becomes entangled in a complex web of crime, corruption, and moral ambiguity, he embarks on a quest to stop Johan and unravel the secrets behind the enigmatic 'Monster'")
    seed_post77 = Post(title="Monogatari",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796814/mono_bilao9.webp", description="The 'Monogatari Series' is a unique and intricate anime franchise that unfolds the supernatural experiences of Koyomi Araragi, a high school student who becomes entangled with various apparitions, gods, and supernatural beings. After a chance encounter with a vampire, Araragi finds himself navigating a world filled with oddities, all while forming bonds with an array of distinctive characters, including his tsundere classmate Hitagi Senjougahara, the intelligent and playful Hachikuji Mayoi, and the powerful oddity specialist Meme Oshino.")
    seed_post78 = Post(title="The Most Heretical Last Boss Queen",  user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796814/mhlbq_wgo4nk.webp", description="A girl is reborn as the villainess of a fantasy game she once played, and now seeks to avoid her doom by carrying out heroic deeds.")
    seed_post79 = Post(title='Mushoku Tensei: Jobless Reincarnation', image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701797444/mkjr_fqfrcn.jpg",description="Despite being bullied, scorned, and oppressed all of his life, a 34-year-old shut-in still found the resolve to attempt something heroic—only for it to end in a tragic accident. But in a twist of fate, he awakens in another world as Rudeus Greyrat, starting life again as a baby born to two loving parents. Preserving his memories and knowledge from his previous life, Rudeus quickly adapts to his new environment. With the mind of a grown adult, he starts to display magical talent that exceeds all expectations, honing his skill with the help of a mage named Roxy Migurdia. Rudeus learns swordplay from his father, Paul, and meets Sylphiette, a girl his age who quickly becomes his closest friend. As Rudeus' second chance at life begins, he tries to make the most of his new opportunity while conquering his traumatic past. And perhaps, one day, he may find the one thing he could not find in his old world—love.",user_id="3" )
    seed_post80 = Post(title="My Hero Academia", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796814/mha_smiylh.jpg", description="'My Hero Academia' is set in a world where individuals known as 'quirks' manifest superhuman abilities, shaping the course of human society. In this new age, aspiring heroes attend U.A. High School to cultivate their quirks and become professional heroes. Izuku Midoriya, born without a quirk but with an unwavering passion to become a hero, encounters the legendary hero All Might. Recognizing Izuku's potential, All Might passes on his quirk, 'One For All', to him. Thus begins Izuku's journey at U.A. High School, where he faces challenges, makes friends, and strives to become the greatest hero the world has ever seen." )
    seed_post81 = Post(title="Neir", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796812/n_uuktna.jpg", description="The plot follows androids of the YoRHa military force fighting for humanity in a proxy war with alien-created Machine Lifeforms")
    seed_post82 = Post(title="Neon Genesis Evangelion", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796812/nge_mkqggk.webp", description="a group of teenagers who are recruited to pilot special robots, called Evangelions, Evas for short, to battle mysterious monsters known as Angels.")
    seed_post83 = Post(title="Naruto", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796812/nar_qb3ite.webp", description="'Naruto' follows the journey of Naruto Uzumaki, a spirited and determined young ninja with dreams of becoming the strongest ninja and earning the title of Hokage—the leader of his village, Konohagakure. Born with the Nine-Tailed Fox demon sealed within him, Naruto faces prejudice and isolation from his fellow villagers. Undeterred, he embarks on a quest for acceptance and recognition, forming bonds with his teammates Sasuke Uchiha and Sakura Haruno as they train under their sensei, Kakashi Hatake.")
    seed_post84 = Post(title="Naruto Shippuden", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796812/ns_vngion.webp", description="'Naruto: Shippuden'continues the epic journey of Naruto Uzumaki as he matures into a powerful ninja and faces increasingly formidable challenges. The story picks up with Naruto returning to the Hidden Leaf Village after two years of intense training with his mentor Jiraiya. The world has changed during his absence, and the threat of the criminal organization Akatsuki looms large. As Naruto reunites with his friends and allies, including Sasuke Uchiha and Sakura Haruno, they embark on a perilous quest to save the world from the schemes of Akatsuki and unravel the mysteries surrounding Naruto's own destiny.")
    seed_post85 = Post(title="One Piece", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796812/op_l2iycd.jpg", description="'One Piece' follows the adventurous journey of Monkey D. Luffy, a young and ambitious pirate with the goal of becoming the Pirate King by finding the legendary treasure known as 'One Piece'. Luffy, inspired by his childhood hero, Red-Haired Shanks, gains the ability to stretch like rubber after unintentionally eating a Devil Fruit. Accompanied by his diverse and quirky crew, known as the Straw Hat Pirates, Luffy explores the vast and treacherous Grand Line, encountering powerful foes, forming alliances, and uncovering the mysteries of the world, all while pursuing his dream and creating a legacy that will echo through the ages.")
    seed_post86= Post(title="One Punch Man", user_id=randint(1, 10), image= "https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796814/opm_qajkgs.png", description="'One Punch Man' follows the extraordinary life of Saitama, a seemingly ordinary man who, through rigorous training, has achieved unparalleled strength. So powerful that he can defeat any opponent with a single punch. However, Saitama finds himself in a predicament—he grows bored and frustrated by the lack of challenging adversaries. In search of excitement, he joins the Hero Association, a group of superheroes who defend the world from various threats. Despite his overwhelming strength, Saitama struggles with the mundanity of being a hero and yearns for an opponent who can provide a genuine challenge.")
    seed_post87=Post(title="Overlord", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796812/over_zyqher.jpg", description="'Overlord' follows the story of Momonga, a dedicated player of the virtual reality MMORPG (Massively Multiplayer Online Role-Playing Game) 'Yggdrasil'. As the servers are scheduled to shut down, Momonga decides to stay logged in until the last moment. However, when the shutdown time passes, Momonga realizes that the game world has become real, and non-player characters have gained sentience. Trapped in this new reality with his powerful in-game character and the now sentient NPCs, Momonga embarks on a quest to explore the world, unravel its mysteries, and find a way to return home while asserting his dominance as the legendary Overlord.")
    seed_post88 = Post(title="Radiant", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796811/ra_uecq6c.webp", description="In the world of 'Radiant', humans coexist with enigmatic creatures known as Nemesis, mysterious beings that fall from the sky and bring destruction wherever they go. However, a rare few individuals known as Sorcerers survive the encounter with Nemesis and gain the ability to wield powerful magic. Seth, an energetic and optimistic boy, is one such Sorcerer who dreams of defeating the Nemesis and ending the centuries-long conflict. Determined to prove that Sorcerers can be heroes rather than outcasts, Seth embarks on a journey to find the mythical Radiant, a source of magic that gives birth to Nemesis, and destroy it once and for all.")
    seed_post89=Post(title="Ragna Crimson", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796811/rc_hidwv3.jpg", description="in a world where dragons rule sky, sea, and land, dragon hunter Ragna joins forces with the mysterious Crimson to fight the dragons at any cost and destroy the dragon monarchs.")
    seed_post90= Post(title="Ranking of Kings", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796884/rok_vbcl62.webp", description="In a fantastical kingdom, where strength and physical prowess traditionally determine one's worth, Bojji, a young and deaf prince, faces adversity due to his perceived weaknesses. Born without the ability to hear or wield a sword, Bojji is often dismissed by those around him. However, his kind heart and determination set him on a remarkable journey to prove that true strength comes from within. Guided by his loyal friend Kage, a shadowy figure, Bojji sets out to fulfill his dream of becoming a great king despite the doubts of his subjects. Along the way, he encounters various characters, both friend and foe, as he strives to overcome the challenges that come with his unique circumstances. The series weaves a tale of self-discovery, friendship, and the importance of inner strength. As Bojji navigates the complex world of the kingdom, he seeks to redefine the criteria by which kings are ranked and challenge the preconceptions surrounding leadership and power.")
    seed_post91 = Post(title="Rise of the Shield Hero", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796883/rotsh_bjkpt1.webp", description="'The Rising of the Shield Hero' follows the story of Naofumi Iwatani, an ordinary college student who is transported to a parallel world along with three other young men. Each of them is chosen as one of the four Cardinal Heroes, tasked with defending the world from inter-dimensional hordes of monsters known as Waves. Naofumi is bestowed the title of the Shield Hero, the only hero without offensive capabilities, and faces immediate betrayal when falsely accused of a heinous crime. Struggling with mistrust and disdain from the people of the world, Naofumi must overcome adversity. With the help of a demi-human named Raphtalia and other companions he encounters along the way, Naofumi embarks on a journey of growth, revenge, and ultimately becoming the hero the world needs.")
    seed_post92 = Post(title="Redo of Hero", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796884/roh_f7tmcr.jpg", description="Keyaru is a healing magician who is sexually abused repeatedly by others. Using his healing magic, he goes back four years into the past to get revenge on the ones who abused him. 'Healing magicians cannot fight alone'. Keyaru, who was bound by this common knowledge, was exploited again and again by others.")
    seed_post93 = Post(title="Reign of the Seven Spell Blades", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796883/rotssb_lp2epw.avif", description="Follows Oliver Horn as he enters a prestigious magic school named Kimberly. He discovers that not everything is as it seems, with the emergence of labyrinths, monsters, and other threats that endanger the students.")
    seed_post94 = Post(title="Rezero", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796816/re_gmpm4j.jpg", description="'Re:Zero - Starting Life in Another World' follows the story of Subaru Natsuki, a typical high school student who finds himself inexplicably transported to a fantasy world. With no special powers or abilities, Subaru is initially excited about the prospect of living in a magical realm. However, his enthusiasm is short-lived when he realizes he has a unique ability—whenever he dies, time rewinds, and he returns to a specific point in the past. As Subaru navigates this mysterious world, he discovers that he is not the only one with special abilities. He encounters various characters, including Emilia, a half-elf with silver hair, and Rem and Ram, twin maids. However, Subaru's newfound power proves to be a double-edged sword, as he faces numerous challenges, tragedies, and deadly adversaries. Determined to protect those he cares about, Subaru embarks on a journey of self-discovery, unraveling the mysteries of the world and confronting his own limitations.")
    seed_post95= Post(title="Rurouni Kenshin", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796884/rk_ehr82m.avif", description="'Rurouni Kenshin' is a classic anime and manga series set in the Meiji era of Japan, following the journey of Himura Kenshin, a wandering swordsman with a dark past. Kenshin, once an infamous assassin during the Bakumatsu period, has since vowed never to kill again and seeks atonement for his past sins. Carrying a sakabatou, a reverse-blade sword that symbolizes his commitment to non-lethal combat, Kenshin travels the countryside as a wandering swordsman known as a 'rurouni' (wanderer). His encounters lead him to Tokyo, where he befriends Kaoru Kamiya, the owner of a kendo dojo, and others who become part of his unconventional but close-knit circle. As Kenshin becomes entangled in various conflicts, both personal and political, his peaceful journey is threatened by adversaries from his past, forcing him to confront the lingering shadows of the Bakumatsu era.")
    seed_post96=Post(title="Saint Seiya", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796876/ss_frc24w.jpg", description="A group a young warriors known as 'Saints', each in possession of a 'cloth' guarded by a different constellation, must protect the reincarnation of the goddess Athena as she attempts to keep the Earth from being destroyed by evil forces.")
    seed_post97 = Post(title="Seven Deadly Sins", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796879/sds_j68eif.webp", description="'The Seven Deadly Sins' is a fantasy anime set in the medieval-like Kingdom of Liones. The story begins when the kingdom is overthrown by the Holy Knights, who betray their comrades, the group known as The Seven Deadly Sins—legendary warriors who were once the strongest Holy Knights of the realm. The Sins are accused of plotting to overthrow the kingdom themselves, forcing them into hiding. Ten years later, Princess Elizabeth embarks on a journey to find The Seven Deadly Sins and seek their help to reclaim her kingdom. The leader of the Sins, Meliodas, along with his companions—Diane, Ban, King, Gowther, Merlin, and Escanor—must reunite to confront the true threat to the kingdom, the corrupt Holy Knights, and uncover the mysteries surrounding the ancient and powerful entities known as the Ten Commandments.")
    seed_post98=Post(title="Seven Knights Revolution", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796876/skr_m31xpw.jpg", description="An ordinary boy named Nemo is saved by a girl named Faria from the forces of destruction. During the ensuing battle, Nemo summons the power of a hero and becomes a successor and so an epic journey where the past and present collide begins.")
    seed_post99 = Post(title="Shaman King", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796879/sk_p3dbze.jpg", description="Shaman King follows the journey of Yoh Asakura, a laid-back and easygoing teenager with a unique gift—he can see and communicate with spirits. In a world where shamans harness the power of spirits to become powerful warriors, Yoh aspires to become the Shaman King, the one who can communicate with the Great Spirit and reshape the world. Guided by his guardian spirit, Amidamaru, and supported by his friends, including Manta Oyamada and the samurai spirit Ryu, Yoh enters the Shaman Fight, a tournament where shamans from around the world compete to become the Shaman King. Along the way, he encounters formidable opponents, uncovers the secrets of his family's past, and faces the malevolent forces that threaten the balance between the worlds of the living and the dead.")
    seed_post100 = Post(title="Shikimoris not just a Cutie", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796876/snjac_wey9lv.webp", description="Shikimori and Izumi are high school sweethearts. They hold hands walking home from school, they flirt in the halls, they tease each other. But Shikimori knows what she wants, and how to get it, and she can turn from cutie to cool in an instant.")
    seed_post101= Post(title="Soul Eater", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796879/se_toscxx.png", description="Soul Eater is a unique and stylized anime set in the fictional Death City, where the Death Weapon Meister Academy (DWMA) is located. The academy is run by Shinigami, also known as Death, and is dedicated to training Meisters and their Demon Weapons, humans who can transform into powerful weapons. The goal of these partnerships is to create Death Scythes, weapons powerful enough to be wielded by Shinigami himself. The story primarily follows three main pairs: Maka Albarn and her scythe partner Soul Eater, Black☆Star and his weapon partner Tsubaki Nakatsukasa, and Death the Kid with his twin pistol partners, Liz and Patty Thompson. Together, they embark on missions to collect evil souls and witches' souls to prevent the awakening of the sinister being known as the Kishin.")
    seed_post102 = Post(title="Scissor Seven", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796879/scs_htzszp.jpg", description="Scissor Seven is an animated series that follows the misadventures of a hairdresser and part-time assassin, known only by his self-proclaimed codename, Scissor Seven. Despite his seemingly harmless profession, Scissor Seven harbors a secret—his scissors double as deadly weapons, turning him into a skilled and unconventional killer. With a case of amnesia that clouds his past, Scissor Seven takes on various odd jobs, taking advantage of his dual identity as a hairdresser and an assassin. As he navigates through a world filled with eccentric characters, mysterious organizations, and unexpected challenges, Scissor Seven strives to uncover the truth about his own past while leaving a stylish mark on both his clients' hair and his adversaries.")
    seed_post103 = Post(title="Spare Me, Great Lord", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796876/spgl_e0pwcl.jpg", description="Lu Shu, the protagonist of the novel Spare Me, Great Lord!. He is abandoned by his parents at a young age, only retaining a walnut-shaped pendant from them. When he gets into a car accident, his pendant manages to save him, while bestowing the distress point system in the process. Travelling under the employment of the Heavenly Network, Lu Shu learns more about the world, and himself.")
    seed_post104 = Post(title="Spy Classroom", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796881/sc_qeczbt.jpg", description="A world where wars are fought with spies. With a mission success rate of 100%, the remarkable, yet rather difficult to deal with, spy Klaus is being tasked with an almost impossible mission by the agency, harboring an insane 90% chance of failure and death... which for some reason involves seven inexperienced girls?!")
    seed_post105 = Post(title="Spy Family", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796879/sf_jiydmw.webp", description="The story follows a spy who has to 'build a family' to execute a mission, not realizing that the girl he adopts as his daughter is a telepath, and the woman he agrees to be in a marriage with is a skilled assassin.")
    seed_post106 = Post(title="Steins Gate", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796879/sg_tv8txf.jpg", description="Steins;Gate is a mind-bending anime that revolves around Rintarou Okabe, a self-proclaimed mad scientist who runs the Future Gadget Laboratory with his friends in Akihabara. Together, they discover a peculiar microwave that can send text messages to the past. As they experiment with time travel, they stumble upon a dark conspiracy that puts their lives and the fate of the world at stake. Okabe's life takes a serious turn when he discovers the consequences of altering the past. He becomes entangled in a web of complex timelines and alternate realities. To navigate this labyrinth, Okabe must confront the secretive organization SERN, face moral dilemmas, and strive to save the people he cares about.")
    seed_post107 = Post(title="Strike the Blood", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796875/stb_zvjx5e.webp", description="Strike the Blood is an anime series that unfolds in a world where supernatural creatures and magic are part of everyday life. Kojou Akatsuki, a seemingly ordinary high school student on the artificial Itogami Island, becomes the Fourth Progenitor—a powerful vampire with abilities that surpass those of traditional vampires. Kojou's peaceful life takes a sudden turn when Yukina Himeragi, a skilled but inexperienced sword shaman, is dispatched to monitor him. As the two become unlikely allies, they find themselves entangled in a series of supernatural incidents and conflicts that threaten the delicate balance of power on Itogami Island. As Kojou grapples with his newfound abilities and the responsibilities of being the Fourth Progenitor, he must navigate a world filled with dangerous entities, political intrigue, and ancient conspiracies.")
    seed_post108 = Post(title="Tower of God", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796869/tog_kea2ew.jpg", description="Tower of God follows the story of a young boy named Bam, who, after encountering a mysterious girl named Rachel, decides to enter the Tower—a colossal, enigmatic structure that promises the fulfillment of one's deepest desires at its peak. The Tower is a world filled with perilous challenges, intricate tests, and powerful adversaries. As Bam ascends the Tower, he forms alliances with other climbers, including the formidable Khun Aguero Agnes and the skilled swordsman Rak Wraithraiser. Each floor of the Tower presents new trials and tests, and climbers must navigate complex relationships, face moral dilemmas, and confront the mysteries surrounding the Tower's origins.")
    seed_post109= Post(title="Tales of Zestria", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796869/toz_ecb65t.jpg", description="Tales of Zestiria the X is an anime adaptation of the popular 'Tales of Zestiria' video game, part of the long-running 'Tales of' series. The story is set in a fantastical world where humans and supernatural beings coexist, and the balance between the two is maintained by a chosen hero. The narrative follows Sorey, a young man with a strong sense of justice who dreams of exploring the mysterious ruins that dot the landscape. His life takes an unexpected turn when he encounters Alisha, a princess on a mission to save her kingdom from a malevolent force known as the 'Hellions'. This encounter leads Sorey to discover his destiny as the Shepherd, a legendary hero tasked with purifying the land and freeing it from the malevolence that plagues it. As Sorey embarks on his journey, he forms bonds with various allies, including the seraph Mikleo and the human knight Rose. Together, they confront the dark forces threatening to plunge the world into chaos.")
    seed_post110 = Post(title= "The Promised Neverland", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796869/tpn_t6g9dq.jpg", description="The Promised Neverland is a psychological thriller that unfolds within the confines of Grace Field House, an idyllic orphanage where children live happily under the care of their 'Mother', Isabella. The story centers on three prodigious orphans—Emma, Norman, and Ray—who discover a dark and unsettling truth about their existence. As the trio stumbles upon the horrifying reality that their beloved orphanage is a front for a sinister operation, their lives take a dramatic turn. The children realize they are being raised as livestock for a species of demonic beings known as Demons. With their graduation intended to be a ticket to the dinner table of these malevolent creatures, Emma, Norman, and Ray must orchestrate a daring escape while unraveling the mysteries surrounding the orphanage and the outside world.")
    seed_post111= Post(title='The Time I Got Reincarnated as A Slime',image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701797258/slime_hgxhzv.webp" ,description="Lonely thirty-seven-year-old Satoru Mikami is stuck in a dead-end job, unhappy with his mundane life, but after dying at the hands of a robber, they awaken to a fresh start in a fantasy realm... as a slime! As Rimuru acclimates to their new, goopy, existence, their exploits with the other monsters set off a chain of events that will change the world forever!", user_id="2")
    seed_post112 = Post(title="Tokyo 24th Ward", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796870/t2w_y1su0z.webp", description="On an artificial island in Tokyo Bay there is a special district commonly known as the 24th Ward, childhood friends Ran, Koki and Shuta hung out together. Their lives changed when their school caught on fire and Koki's sister Asumi was caught inside.")
    seed_post113= Post(title="Trigun", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796870/tg_hclmoc.webp", description="Trigun is a classic anime that takes place on the desert planet Gunsmoke, where outlaws and bounty hunters roam the vast wastelands. The story follows Vash the Stampede, a mysterious gunslinger with a reputation for leaving destruction in his wake. Despite being pursued by bounty hunters seeking the reward on his head, Vash is known for his strict policy of never taking a life. As Vash's true identity and the reasons behind the bounty on his head gradually come to light, he finds himself entangled in a web of conspiracies and encounters a diverse cast of characters. Along the way, Vash's pacifist ideals clash with the harsh realities of the world, leading to both humorous and poignant moments.")
    seed_post114 =Post(title="Tsugumomo", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796865/tsu_a2otas.jpg", description="Kazuya Kagami, an ordinary boy, finds his life turned upside down when his late mother's obi transforms into a girl wearing a kimono named Kiriha. She happens to be a tsukumogami called a 'tsugumomo', objects that have gained a soul through long years of harmony with their owners.")
    seed_post115 = Post(title="Tsukimichi Moonlit Fantasy", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796869/tmf_cbdo8t.jpg", description="Makoto Misumi was just an average teenager who suddenly was summoned to another world as a 'hero'. But the goddess of this world called him ugly and took his hero status away from him, then sent him to the ends of the world.")
    seed_post116 = Post(title="Tsuyokute New Saga", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796869/tns_vgknxw.jpg", description="The story follows adventurer Kyle, who finds himself transported four years into the past to the beginning of the demon invasion, right as he was about to finish off the final boss. Armed with the memories and skills he gained in that time, he'll endeavor to prevent the same tragedies from occurring.")
    seed_post117 = Post(title="Undead Murder Farce", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796863/umf_qhd5sh.jpg", description="In a world inhabited by vampires, golems, werewolves and other creatures, Aya Rindo, along with Tsugaru Shunichi and Shizuku Hasei, travels as supernatural detective, solving mysteries while she looks for her lost body.")
    seed_post118 = Post(title="Undead Unlock", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796862/uu_hutcm8.webp", description="UNDEAD UNLUCK centers around a woman named Fuuko who has the supernatural ability to cause 'unluck' -- usually an extreme death -- for anyone who touches her skin.")
    seed_post119 = Post(title="The World's Greatest Assassin Get Reincarnated As an Aristocrat", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796863/twgagraaa_eejjqo.webp", description="The world's number one assassin has been reincarnated as the eldest son of a family of aristocrat assassins. In exchange for being reincarnated in another world, a goddess has imposed upon him one condition. 'Kill the Hero who is prophesied to destroy the world.' This was to be the mission in his new life.")
    seed_post120 = Post(title="Xam'd Lost Memories", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796862/xlm_svsi0a.webp", description="Akiyuki Takehara, a high school student, who becomes involved in a terrorist attack and is given the power to transform into a creature known as a Xam'd, along with his interactions with Haru Nishimura, Akiyuki's friend who attempts to rendezvous with him, and Nakiami, a mysterious girl who helps Akiyuki to control the Xam'd power inside of him.")
    seed_post121 = Post(title="Zatch Bell", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796862/zb_uapwxv.webp", description="The story revolves around a mysterious, amnesiac child named Zatch Bell and his human partner Kiyo Takamine. Zatch is a Mamodo, a kind of supernatural being from another world, and he has a spellbook that contains powerful spells. The Mamodo pairs, consisting of a Mamodo and a human partner, battle each other in a tournament known as the 'Mamodo Battle' to determine the king of the Mamodo world.")
    seed_post122 = Post(title="Zom 100: Bucket List of The Dead", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796862/z100_fjt51d.jpg", description="an overworked 24-year-old finally decides to live a little and create a bucket list, when a zombie outbreak hits the country.")
    seed_post123 = Post(title="91 Days", user_id=randint(1, 10), image="https://res.cloudinary.com/dpdvw1sam/image/upload/v1701796846/91_tl8d9m.jpg", description="91 Days is an anime love letter to mafia films. Set in the 1930s when Prohibition is in full effect, its cast is filled with gangsters and bootleggers, led by a protagonist on a single-minded quest for revenge.")







    all_posts = [seed_post1, seed_post2, seed_post3, seed_post4, seed_post5, seed_post6,
                 seed_post7, seed_post8, seed_post9, seed_post10, seed_post11, seed_post12,seed_post13, seed_post14,
                 seed_post15, seed_post16,seed_post17, seed_post18, seed_post19, seed_post20, seed_post21, seed_post22,
                 seed_post23, seed_post24, seed_post25,seed_post26, seed_post27, seed_post28, seed_post29, seed_post30,
                 seed_post31, seed_post32, seed_post33, seed_post34, seed_post35, seed_post36, seed_post37, seed_post38,
                 seed_post39, seed_post40, seed_post41, seed_post42, seed_post43, seed_post44, seed_post45, seed_post45,
                 seed_post46, seed_post47, seed_post48, seed_post49, seed_post50, seed_post51, seed_post52, seed_post53,
                 seed_post54, seed_post55, seed_post56, seed_post57, seed_post58, seed_post59, seed_post60, seed_post61,
                 seed_post62, seed_post63, seed_post64, seed_post65, seed_post66, seed_post67, seed_post68, seed_post69,
                 seed_post70, seed_post71, seed_post72, seed_post73, seed_post74, seed_post75, seed_post76, seed_post77,
                 seed_post78, seed_post79, seed_post80, seed_post81, seed_post82, seed_post83, seed_post84, seed_post85,
                 seed_post86, seed_post88, seed_post89, seed_post90, seed_post91, seed_post92, seed_post93, seed_post94,
                 seed_post95, seed_post96, seed_post97, seed_post98, seed_post99, seed_post100, seed_post101, seed_post102,
                 seed_post103, seed_post104, seed_post105, seed_post106, seed_post107, seed_post108, seed_post109, seed_post110,
                 seed_post111, seed_post112, seed_post113, seed_post114, seed_post115, seed_post116, seed_post117, seed_post118,
                 seed_post119, seed_post120, seed_post121, seed_post122, seed_post123
                ]
    add_posts = [db.session.add(post) for post in all_posts]
    db.session.commit()


def undo_posts():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.posts RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM posts"))

    db.session.commit()
