"""empty message

Revision ID: d11e3fdca039
Revises:
Create Date: 2023-12-04 17:34:08.128127

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'd11e3fdca039'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('adminKey', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")

    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2500), nullable=False),
    sa.Column('userId', sa.String(length=40), nullable=False),
    sa.Column('categoriesId', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoriesId'),
    sa.UniqueConstraint('userId')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE posts SET SCHEMA {SCHEMA};")


    # ### end Alembic commands ###
    # op.create_table('postCategories',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('postId', sa.Integer(), nullable=True),
    # sa.Column('categoryId', sa.Integer(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )

    # if environment == "production":
    #     op.execute(f"ALTER TABLE postCategories SET SCHEMA {SCHEMA};")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('posts')
    op.drop_table('postCategories')
    # ### end Alembic commands ###
